Repository Oh3gwnn/Project_Closetalk, pull requests merged in 2023-09, with the labels that each got.

#54 CLTK-51 : 커뮤니티 게시물 생성 및 수정
  src/main/java/team/closetalk/community/controller/CommunityArticleController.java
  src/main/java/team/closetalk/community/dto/CommunityArticleDto.java
  src/main/java/team/closetalk/community/dto/CommunityArticleListDto.java
  src/main/java/team/closetalk/community/entity/CommunityArticleEntity.java
  src/main/java/team/closetalk/community/enumeration/Category.java
  src/main/java/team/closetalk/community/repository/CommunityArticleRepository.java
  src/main/java/team/closetalk/community/service/CommunityArticleService.java
Labels: 🔨 Refactor, ✨ Feature

#57 CLTK-51 : 게시물 생성 수정 - 이미지 관련
  src/main/java/team/closetalk/community/controller/CommunityArticleController.java
  src/main/java/team/closetalk/community/dto/CommunityCommentReplyDto.java
  src/main/java/team/closetalk/community/dto/CommunityCreateArticleDto.java
  src/main/java/team/closetalk/community/entity/CommunityArticleEntity.java
  src/main/java/team/closetalk/community/entity/CommunityArticleImagesEntity.java
  src/main/java/team/closetalk/community/entity/CommunityCommentEntity.java
  src/main/java/team/closetalk/community/service/CommunityArticleSaveImageService.java
  src/main/java/team/closetalk/community/service/CommunityArticleService.java
Labels: ✨ Feature

#60 CLTK-51 : 커뮤니티 게시물 생성(with CLOSET)
  src/main/java/team/closetalk/closet/service/EntityRetrievalService.java
  src/main/java/team/closetalk/community/controller/CommunityArticleController.java
  src/main/java/team/closetalk/community/controller/CommunitySearchController.java
  src/main/java/team/closetalk/community/dto/article/request/CommunityCreateArticleDto.java
  src/main/java/team/closetalk/community/dto/article/response/CommunityArticleDto.java
  src/main/java/team/closetalk/community/dto/article/response/CommunityArticleImagesDto.java
  src/main/java/team/closetalk/community/dto/article/response/CommunityArticleListDto.java
  src/main/java/team/closetalk/community/entity/CommunityArticleEntity.java
  src/main/java/team/closetalk/community/entity/CommunityArticleImagesEntity.java
  src/main/java/team/closetalk/community/entity/CommunityCommentEntity.java
  src/main/java/team/closetalk/community/entity/composite/ArticleClosetItemId.java
  src/main/java/team/closetalk/community/entity/composite/CommunityArticleClosetItems.java
  src/main/java/team/closetalk/community/repository/ArticleAndClosetItemRepository.java
  src/main/java/team/closetalk/community/repository/CommunityArticleImagesRepository.java
  src/main/java/team/closetalk/community/repository/CommunityCommentRepository.java
  src/main/java/team/closetalk/community/repository/CommunitySearchRepository.java
  src/main/java/team/closetalk/community/service/CommunityArticleSaveImageService.java
  src/main/java/team/closetalk/community/service/CommunityArticleService.java
  src/main/java/team/closetalk/community/service/CommunityCommentService.java
  src/main/java/team/closetalk/community/service/CommunitySearchService.java
Labels: 🔨 Refactor, ✨ Feature

#73 CLTK-74 : OOTD 좋아요 기능 및 좋아요 글 목록 조회
  src/main/java/team/closetalk/mypage/controller/LikeArticleController.java
  src/main/java/team/closetalk/mypage/repository/LikedArticleRepository.java
  src/main/java/team/closetalk/mypage/service/LikedArticleService.java
  src/main/java/team/closetalk/ootd/controller/OotdRestController.java
  src/main/java/team/closetalk/ootd/dto/OotdArticleDto.java
  src/main/java/team/closetalk/ootd/dto/OotdLikeDto.java
  src/main/java/team/closetalk/ootd/entity/OotdArticleEntity.java
  src/main/java/team/closetalk/ootd/entity/OotdLikeEntity.java
  src/main/java/team/closetalk/ootd/repository/OotdLikeRepository.java
  src/main/java/team/closetalk/ootd/service/OotdLikeService.java
Labels: 🔨 Refactor, ✨ Feature

#84 CLTK-2-dev : redis, refresh token 관련 기능 추가 및 내 옷장 페이지 추가
  src/main/java/team/closetalk/closet/controller/ClosetController.java
  src/main/java/team/closetalk/closet/controller/ClosetViewController.java
  src/main/java/team/closetalk/user/controller/UserController.java
  src/main/java/team/closetalk/user/controller/ViewController.java
  src/main/java/team/closetalk/user/service/TokenService.java
  src/main/java/team/closetalk/user/service/UserService.java
  src/main/java/team/closetalk/user/utils/JwtFilter.java
  src/main/java/team/closetalk/user/utils/JwtSecretKeyGenerator.java
  src/main/java/team/closetalk/user/utils/JwtUtils.java
  src/main/java/team/closetalk/user/utils/OAuth2SuccessHandler.java
  src/main/resources/static/images/closetItem/userNo.1/MyCloset1/nike.png
  src/main/resources/static/images/closetItem/userNo.1/MyCloset1/nikets.png
  src/main/resources/static/images/closetItem/userNo.1/아우터모음/adidas.png
  src/main/resources/static/images/closetItem/userNo.1/아우터모음/cc.jpg
  src/main/resources/static/js/closet/MyCloset.js
  src/main/resources/static/js/setToken.js
  src/main/resources/templates/closet/my-closet.html
  src/main/resources/templates/user/test.html
Labels: ⚙ Setting, ✅ Test, 🔨 Refactor, 🎨 Html&css, 🌏 Deploy, ✨ Feature, 🐞 BugFix

#86 CLTK-72 : DM 기능 구현
  src/main/java/team/closetalk/community/repository/CommunityArticleRepository.java
  src/main/java/team/closetalk/mypage/config/WebSocketConfig.java
  src/main/java/team/closetalk/mypage/controller/DMController.java
  src/main/java/team/closetalk/mypage/controller/DMViewController.java
  src/main/java/team/closetalk/mypage/controller/LikeArticleController.java
  src/main/java/team/closetalk/mypage/dto/DMRoomRequestDto.java
  src/main/java/team/closetalk/mypage/dto/DMRoomResponseDto.java
  src/main/java/team/closetalk/mypage/dto/MessageDto.java
  src/main/java/team/closetalk/mypage/entity/dm/DMRoom.java
  src/main/java/team/closetalk/mypage/entity/dm/DMUser.java
  src/main/java/team/closetalk/mypage/entity/dm/Message.java
  src/main/java/team/closetalk/mypage/repository/DMRoomRepository.java
  src/main/java/team/closetalk/mypage/repository/DMUserRepository.java
  src/main/java/team/closetalk/mypage/repository/LikedArticleRepository.java
  src/main/java/team/closetalk/mypage/repository/MessageRepository.java
  src/main/java/team/closetalk/mypage/service/DMService.java
  src/main/java/team/closetalk/mypage/service/LikedArticleService.java
  src/main/resources/templates/dm/direct-message.html
Labels: ✨ Feature
